nginx:
    image: nginx:alpine
    ports:
        - 8000:80
    links:
        - php
    volumes:
        - ./source:/var/www/html
        - ./sites:/etc/nginx/conf.d

php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
        - memcached  
    volumes:
        - ./source:/var/www/html

mysql:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
        - ./data:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8100:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql

memcached:
    image: memcached:latest
    
